config/routes.rb
Rails.application.routes.draw do

  root 'application#welcome'
  resources :user_produce, only: [:show, :update]
  post "user_produce/:id" => "user_produce#create"
  resources  :produce, :juice_produce, :juices, :comments
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/auth/facebook/callback' => 'sessions#create'
  get '/privacy-policy' => 'privacy_policy#privacy_policy'

  resources :users do
    resources :juices, only: [:index, :new]
  end

  resources :produce do
    resources :juices, only: :index
  end

  get 'users/:id/produce/index' => 'produce#index', as: :user_user_produce_index
  get '/welcome' => 'application#welcome'
  get '/demo' => 'application#demo'
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and
  devise :omniauthable, :omniauth_providers => [:facebook]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  validates :name, :email, presence: true
  validates :name, :email, uniqueness: true
  validates :email, format: { with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i }
  validates :email, length: { :minimum => 8 }
  has_many :user_produce
  has_many :produce, through: :user_produce
  has_many :juices
  has_many :comments

  def current_produce
    self.user_produce.where(eaten?: false)
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.save
    end
  end

  def sorted
    self.juices.sort_by {|juice| juice.name}
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "site"
  before_action :logged_in?

  def show

  end

  def index
    @users = User.all
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 100)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end


  def edit(current_user)
    if current_user.provider == nil
      edit_user_registration_path(current_user)
    else
      edit_user_path(current_user)
    end
  end
end

app/views/users/_user_produce.html.erb
<% produce.each do |prod| %>
<div clas="row ">
  <div class="col-md-6 text-center">
    <h2 align='center'><%= prod.produce.name %></h2>
    <div class="produce-img">
      <%= link_to image_tag(prod.produce.image.thumb.url), produce_path(prod.produce) %>
    </div><br>
    <%= "Expires in #{prod.shelf_life} days" %>
    <br></br>
    <%= button_to "I ate it!", eaten_path(prod), class: 'btn btn-default' %>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <h1>Edit User</h1>
    <hr>
    <h3>Name <%= current_user.name %></h3>
    <h3>Email <%= current_user.email %></h3>
    <hr>

    <h2>Cancel my account</h2>

    <p>Unhappy? <%= button_to "Cancel my account", registration_path(current_user), class: "btn btn-danger", data: { confirm: "Are you sure? You cannot undo this." }, method: :delete %></p>

    <%= link_to "Back", :back %>
    <hr>
  </div>
</div>

app/views/users/index.html.erb
<h1>Friends With Produce</h1>
<ul class="users">
  <% @users.each do |user| %>
  <li>
    <%= gravatar_for user, size: 50 %>
    <%= user.name %>
  </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= render partial: 'shared/jumbotron', locals: { jumbo: 'jumbotron-user', header: "#{current_user.name}'s profile" }%>
<div class="container">
  <div class="row">
    <aside class="col-md-4 col-md-offset-1">
      <section class ="user_info">
        <h3>
          <%= gravatar_for current_user %>
          <%= current_user.name %><br>
          <%= current_user.email %>
        </h3>
        <%= link_to "Edit", edit(current_user) %>
      </section>
    </aside>

  </div>
</div>


<script type="text/javascript">
  $(function() {
    userJuice();
  });
</script>