config/routes.rb
Rails.application.routes.draw do

  root 'application#welcome'
  resources :user_produce, only: [:show, :update]
  post "user_produce/:id" => "user_produce#create"
  resources  :produce, :juice_produce, :juices, :comments
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/auth/facebook/callback' => 'sessions#create'
  get '/privacy-policy' => 'privacy_policy#privacy_policy'

  resources :users do
    resources :juices, only: [:index, :new]
  end

  resources :produce do
    resources :juices, only: :index
  end

  get 'users/:id/produce/index' => 'produce#index', as: :user_user_produce_index
  get '/welcome' => 'application#welcome'
  get '/demo' => 'application#demo'
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash_messages.html.erb
<% if flash.present? %>
  <div id="flash">
    <script>
      <% if flash[:success] %>
        toastr.success("<%= flash[:success] %>")
      <% end %>
      <% if flash[:info] %>
        toastr.success("<%= flash[:info] %>")
      <% end %>
      <% if flash[:notice] %>
        toastr.success("<%= flash[:notice] %>")
      <% end %>
      <% if flash[:alert] %>
        toastr.error("<%= flash[:alert] %>")
      <% end %>
    </script>
  </div>
<% end %>

app/views/shared/_home_navigation.html.erb
<% if current_user.nil? %>
  <%= link_to image_tag("wilt_no_more2.png"), welcome_path, class: 'navbar-brand' %>
<% else %>
  <%= link_to image_tag("wilt_no_more2.png"), user_produce_path(current_user), class: 'navbar-brand' %>
<% end %>

app/views/shared/_jumbotron.html.erb
<div class="jumbotron <%= jumbo %>">
  <div class="img"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="jumbo-header" align="center"><%= header %></h1>
      </div>
    </div>
    <br> <br/>

    <% if current_user && !@juices %>
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <% if @user_produce %>
            <div class="col-md-6 row-centered">
              <%= link_to "Add Produce to Fridge", produce_index_path, class: 'btn btn-green btn-block' %>
            </div>
            <div class="col-md-6 row-centered">
              <%= link_to "See Your Favorite Produce", user_user_produce_index_path(current_user), class: 'btn btn-green btn-block' %>
            </div>
          <% elsif @produce %>
            <div class="col-md-6 row-centered">
              <%= link_to "See What's in Your Fridge", user_produce_path(current_user), class: 'btn btn-green btn-block' %>
            </div>
            <div class="col-md-6 row-centered">
              <%= link_to "See Your Favorite Produce", user_user_produce_index_path(current_user), class: 'btn btn-green btn-block' %>
            </div>
          <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<hr class="hr-green">

app/views/shared/_login_navigation.html.erb
<li><%= link_to "Demo", demo_path %></li>
<li><%= link_to "Log In", new_user_session_path %></li>
<li><%= link_to "Sign Up", new_user_registration_path %></li>

app/views/shared/_messages.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-fixed-top <%= navbar_color %>" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= render 'shared/home_navigation' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <%= render 'shared/navigation' %>
        <% else %>
          <%= render 'shared/login_navigation' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navigation.html.erb
<% if current_user.nil? %>
  <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %></li>
  <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: 'nav-link' %></li>
<% else %>
  <li class="nav-item"><%= link_to "Fridge", user_produce_path(current_user), class: 'nav-link' %></li>
  <li class="nav-item"><%= link_to "Produce", produce_index_path, class: 'nav-link' %></li>
  <li class="nav-item"><%= link_to "Juices", juices_path, class: 'nav-link' %></li>
  <li class="nav-item"><%= link_to "#{current_user.name}", user_path(current_user), class: 'nav-link' %></li>
  <li class="nav-item"><a class='nav-link' data-method="delete" href="/users/sign_out" rel="nofollow">Sign Out</a></li>
<% end %>