config/routes.rb
Rails.application.routes.draw do

  root 'application#welcome'
  resources :user_produce, only: [:show, :update]
  post "user_produce/:id" => "user_produce#create"
  resources  :produce, :juice_produce, :juices, :comments
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/auth/facebook/callback' => 'sessions#create'
  get '/privacy-policy' => 'privacy_policy#privacy_policy'

  resources :users do
    resources :juices, only: [:index, :new]
  end

  resources :produce do
    resources :juices, only: :index
  end

  get 'users/:id/produce/index' => 'produce#index', as: :user_user_produce_index
  get '/welcome' => 'application#welcome'
  get '/demo' => 'application#demo'
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/produce.rb
class Produce < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :user_produce
  has_many :users, through: :user_produce
  has_many :juice_produce, dependent: :destroy
  has_many :juices, through: :juice_produce
  before_save { self.name = name.titleize }
  mount_uploader :image, ImageUploader
  accepts_nested_attributes_for :juices, :juice_produce

  def self.fruit
    self.where(kind: 'fruit').order(:name)
  end

  def self.veggies
    self.where(kind: 'veggie').order(:name)
  end

  def self.faves
    group(:id).order("count(produce.id) DESC").limit(6)
  end

  def self.sorted
    self.all.sort_by {|prod| prod.name}
  end

  def next
    Produce.where("id > ?", id).limit(1).first
  end

  def prev
    Produce.where("id < ?", id).limit(1).first
  end
end

app/controllers/produce_controller.rb
class ProduceController < ApplicationController
  layout "site"
  include ProduceHelper
  before_action :logged_in?, except: :index

  def index
    index_helper(params)
  end

  def new
    @produce = Produce.new
  end

  def create
    @produce = Produce.new(produce_params)
    if @produce.save
      flash[:success] = "You are quite the #{@produce.name} lover!"
      redirect_to @produce
    else
      flash[:alert] = "Item was not saved. Please fill in all fields."
      render :new
    end
  end

  def show
    @produce = Produce.find(params[:id])
    @last_produce_id = Produce.last.id
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @produce }
    end
  end

  def edit
    @produce = Produce.find(params[:id])
  end

  def update
    @produce = Produce.find(params[:id])
    @produce.update_attributes(produce_params)
    if @produce.save
      flash[:success] = "#{@produce.name} was successfully edited"
      redirect_to @produce
    else
      flash[:alert] = "The item was not edited"
      render :edit
    end
  end

  def destroy
    @produce = Produce.find(params[:id])
    @produce.destroy
    flash[:success] = "#{@produce.name} was deleted"
    redirect_to produce_index_path
  end

  private

  def produce_params
    params.require(:produce).permit(:name, :image, :kind, :content, :expires_in, :content)
  end
end

app/helpers/produce_helper.rb
module ProduceHelper

  def index_helper(params)
    if params[:id]
      @fruit = User.find(params[:id]).produce.fruit.faves
      @veggies = User.find(params[:id]).produce.veggies.faves
      @produce_jumbo = "#{current_user.name}'s Faves"
    else
      @fruit = Produce.fruit
      @veggies = Produce.veggies
      @produce_jumbo = "Fresh Produce"
    end
  end
  
end

app/views/produce/_form.html.erb
<%= bootstrap_form_for(@produce) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :expires_in, label: 'How many days does it last?' %>
  <%= f.select(:kind, [ 'fruit', 'veggie' ], {}, { class: 'select'}) %>
  <%= f.text_area :content, label: 'Tell us about this item (benefits and such)' %>
  <%= f.file_field :image %>

  <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/produce/_produce.html.erb
<% produce.each do |produce| %>
<div clas="row">
  <div class="col-md-6 text-center produce-card">
    <h3 align='center'><%= produce.name %></h3>
    <div class="produce-index-img text-center">
      <%= link_to image_tag(produce.image.thumb.url), produce_path(produce) %>
    </div>
    <br></br>
    <%= button_to "Add to Fridge", user_produce_path(produce), remote: true, class: "btn btn-default add-to-fridge" if user_signed_in? %>
  </div>
</div>
<% end %>

app/views/produce/edit.html.erb
<div class="col-md-6 col-md-offset-3">

  <h1>Edit Produce</h1>
  <%= render 'form' %>
  <p align="right"><%= link_to "I don't want to edit", produce_index_path %></p>
</div>

app/views/produce/index.html.erb
<%= render partial: "shared/jumbotron", locals: {jumbo: 'jumbotron-produce', header: @produce_jumbo} %>
<div class="container-fluid">
  <div class="col-xs-6 col-md-6">
    <h2 align='center'>Fruit</h2>
    <%= render partial: "produce/produce", locals: {produce: @fruit} %>
  </div>
  <div class="col-xs-6 col-md-6">
    <h2 align='center'>Veggies</h2>
    <%= render partial: "produce/produce", locals: {produce: @veggies} %>
  </div>
</div><br>
<h3 align="center"><%= link_to "Don't see what you want?", new_produce_path if user_signed_in?%></h3>

app/views/produce/new.html.erb
<div class="col-md-6 col-md-offset-3">

  <h1>New Produce</h1>
  <%= bootstrap_form_for(@produce) do |f| %>
    <%= f.text_field :name %>
    <%= f.text_field :expires_in, label: 'How many days does it last?' %>
    <%= f.select(:kind, [ 'fruit', 'veggie' ], {}, { class: 'select'}) %>
    <%= f.text_area :content, label: 'Tell us about this item (benefits and such)' %>
    <%= f.file_field :image %>

    <%= f.submit "Create Produce", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/produce/show.html.erb
<div class="produceBody">
  <div class="row produce-row">
    <h1 align="center" class="produceName"><%= @produce.name %></h1>
    <div class="text-center col-md-4 col-md-offset-2 produceImage" >
      <%= image_tag @produce.image.large.url %>
    </div>
    <div class="col-md-4 info">
      <h4 class="produceContent"><%= @produce.content %></h4>
      <h4 id="expiresIn">Shelf life is usually about <%= @produce.expires_in %> days.</h4>
      <br></br>
      <%= link_to "Add to Fridge", user_produce_path(@produce), method: 'post', class: "btn btn-default btn-block", remote: true %>
      <%= link_to "Edit Produce Item", edit_produce_path(@produce), class: "btn btn-default btn-block" %>
      <%= link_to "Juices with #{@produce.name}", produce_juices_path(@produce), class: "btn btn-default btn-block" %>
    </div>
  </div>
  </br>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="col-md-4 col-md-offset-4" align="center">
        <a href="#" class="js-previous" data-id="<%= @produce.id %>">Previous Item</a>
        ------  <a href="#" class="js-next" data-id="<%= @produce.id %>" last-id="<%= @last_produce_id %>">Next Item</a>
      </div>
    </div>
  </div>
</div>

<script id="nextPrevProduce-template" type="text/x-handlebars-template">
  <div class="produceBody">
    <div class="row produce-row">
      <h1 align="center" class="produceName">{{name}}</h1>
      <div class="text-center col-md-4 col-md-offset-2 produceImage">
        <img src="{{image}}" alt="" />
        <br><br><br><br>
      </div>
      <div class="col-md-4 info">
        <h4 class="produceContent">{{content}}</h4>
        <h4 id="expiresIn">Shelf life is usually about {{shelfLife}} days.</h4>
        <br></br>
        <form action="/user_produce/{{id}}" method="post" data-remote="true">
          <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
          <input class="btn btn-default btn-block" type="submit" value="Add to fridge"/>
        </form>
        <button class="btn btn-default btn-block"><a href="/produce/{{id}}/edit">Edit Produce Item</a></button>
        <button class="btn btn-default btn-block"><a href="/produce/{{id}}/juices">Juices with {{name}}</a></button>
      </div>
    </div>
    </div>
  </div>
  </br>
  <div class="row nextPrevLinks">
    <div class="col-md-6 col-md-offset-3">
      <div class="col-md-4 col-md-offset-4" align="center">
        <a href="#" class="js-previous" data-id="{{id}}">Previous Item</a>
        ------  <a href="#" class="js-next" data-id="{{id}}" last-id="<%= @last_produce_id %>">Next Item</a>
      </div>
    </div>
  </div>
</div>
</script>

<script type="text/javascript">
$(function() {
  previous();
  next();
});
</script>