config/routes.rb
Rails.application.routes.draw do

  root 'application#welcome'
  resources :user_produce, only: [:show, :update]
  post "user_produce/:id" => "user_produce#create"
  resources  :produce, :juice_produce, :juices, :comments
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/auth/facebook/callback' => 'sessions#create'
  get '/privacy-policy' => 'privacy_policy#privacy_policy'

  resources :users do
    resources :juices, only: [:index, :new]
  end

  resources :produce do
    resources :juices, only: :index
  end

  get 'users/:id/produce/index' => 'produce#index', as: :user_user_produce_index
  get '/welcome' => 'application#welcome'
  get '/demo' => 'application#demo'
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/juice.rb
class Juice < ApplicationRecord
  has_many :juice_produce, dependent: :destroy
  has_many :produce, through: :juice_produce
  has_many :comments
  belongs_to :user
  #accepts_nested_attributes_for :produce, :juice_produce, reject_if: proc { |attributes| attributes[:quantity].blank? }, allow_destroy: true
  validates :name, presence: true
  validates :name, uniqueness: true

  def produce_attributes=(produce_attributes)
    produce_attributes.values.each do |produce_attribute|
      if !produce_attribute[:name].empty?
        if produce_attribute[:name].numeric?
          prod = Produce.find(produce_attribute[:name])
        else
          prod = Produce.find_or_create_by(name: produce_attribute[:name])
        end
        if !produce_attribute[:juice_produce_attributes].values.first[:quantity].empty?
          juice_prod = self.juice_produce.find_or_create_by(produce_id: prod.id)
          juice_prod.quantity =  produce_attribute[:juice_produce_attributes].values.first[:quantity]
          juice_prod.save!
        end
      end
    end
  end

  def next
    Juice.where("id > ?", id).limit(1).first
  end

  def prev
    Juice.where("id < ?", id).limit(1).first
  end

  # def produce_attributes?(produce_attributes)
  #   pa = ""
  #   produce_attributes.values.each do |produce_attribute|
  #     pa << produce_attribute[:name]
  #   end
  #   !pa.empty?
  # end

  def self.juices_with_produce(params)
    joins(:juice_produce).where("produce_id =?", params).order(:name)
  end

  def self.sorted
    self.all.sort_by {|juice| juice.name}
  end
end

app/controllers/juices_controller.rb
class JuicesController < ApplicationController
  layout "site"
  before_action :logged_in?
  include JuicesHelper

  def index
    juice_index_helper(params)
    respond_to do |f|
      f.html { render :index }
      f.json { render json: @juices }
    end
  end

  def new
    if params[:user_id].to_i == current_user.id
      @juice = Juice.new
      @produce = Produce.sorted
      @juice.produce.build
      @juice.juice_produce.build
    else
      flash[:alert] = "Hey! That's naughty! Stay on your own form!"
      redirect_to root_path
    end
  end

  def create
    # params[:juice][:produce_attributes].values.first[:name]
    juice_create_helper(params)
  end

  def show
    @juice = Juice.find(params[:id])
    @juice_produce = @juice.juice_produce
    @last_juice_id = Juice.last.id
    @juice_comments = @juice.comments
    @comment = Comment.new
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @juice, include: ['comments', 'comments.user', 'juice_produce', 'produce'] }
    end
  end

  def edit
    @juice = Juice.find(params[:id])
    @produce_juice = @juice.produce
  end

  def update
    @juice = Juice.find(params[:id])
    @juice.update_attributes(juice_params(:name, :produce_attributes => [:id, :name, :juice_produce_attributes => :quantity]))
    if @juice.save
      flash[:success] = "Great success! #{@juice.name} has been edited!"
      redirect_to @juice
    else
      flash[:alert] = "Please add ingredients"
      redirect_to edit_juice_path(@juice)
    end
  end

  def destroy
    @juice = Juice.find(params[:id])
    if current_user.id == @juice.user_id
      @juice.destroy
      flash[:success] = "#{@juice.name} was successfully destroyed. That's good. Nobody liked it anyway!"
      redirect_to juices_path
    else
      flash[:alert] = "Sorry, you do not have permission to delete #{@juice.name}"
      redirect_to @juice
    end
  end

  private

  def juice_params(*args)
    params.require(:juice).permit(*args)
  end
end

app/helpers/juices_helper.rb
module JuicesHelper

  def juice_index_helper(params)
    if params[:user_id]
      @user = User.find(params[:user_id])
      @juices = @user.sorted
      @header = "Juices created by #{@user.name}"
    elsif params[:produce_id]
      @produce = Produce.find(params[:produce_id])
      @juices = Juice.juices_with_produce(params[:produce_id])
      @header = "Juices with #{@produce.name}"
    else
      @juices = Juice.sorted
      @header = "Fresh Juices"
    end
  end

  def juice_create_helper(params)
    if Juice.find_by(name: params[:juice][:name])
      flash[:alert] = "That name has already been taken. Please choose another name."
      redirect_to new_user_juice_path(current_user)
    else
      @juice = Juice.new(juice_params(:name))
      if @juice.save
        @juice.user_id = current_user.id
        @juice.update_attributes(juice_params(:produce_attributes => [:name, :juice_produce_attributes => :quantity]))
        if @juice.save
          redirect_to @juice
        else
          flash[:alert] = "Please add ingredients"
          redirect_to new_user_juice_path(current_user)
        end
      else
        flash[:alert] = "Please name the juice"
        redirect_to new_user_juice_path(current_user)
      end
    end
  end

end

app/views/juices/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1 align="center">Edit Juice</h1>
  <%= bootstrap_form_for @juice do |f| %>
    <h3><%= f.text_field :name %></h3>
    <label><h3 align="center">Ingredients:</h2></label>
    <div class="row">
      <% counter = 0 %>
      <% 4.times do  %>
      <div class="col-xs-3">
        <%= f.fields_for :produce, @juice.produce.build do |prod_builder| %>
          <%= prod_builder.select 'name', options_from_collection_for_select(@juice.produce, 'id', 'name', @juice.produce_ids[counter]), include_blank: true %>
          <%= prod_builder.fields_for :juice_produce, @juice.juice_produce.build do |jp_builder| %>
            <%= jp_builder.number_field :quantity, min: 1, placeholder: "Quantity" %>
          <% end %>
        <% end %>
      </div>
      <% counter +=1 %>
      <% end %>
    </div>
    <div class="row">
      <h4 align="center">Can't find your ingredient? Add it here:</h4>
      <% 4.times do %>
        <div class="col-xs-3">
          <%= f.fields_for :produce, @juice.produce.build do |prod_form| %>
            <%= prod_form.text_field :name, placeholder: "Produce" %>
            <%= prod_form.fields_for :juice_produce, @juice.juice_produce.build do |jp_form| %>
              <%= jp_form.number_field :quantity, placeholder: "Quantity" %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <%= f.submit %>
  </div>
  <% end %>
  <br></br>
</div>
<h4 align="center"><%= link_to "I don't want to edit", juice_path(@juice) %></h4>

app/views/juices/index.html.erb
<%= render partial: "shared/jumbotron", locals: {jumbo: 'jumbotron-juice', header: @header } %>
<div class="container">
  <div class="row row-centered">
    <div class="col-lg-10 col-lg-offset-1">
      <% @juices.each do |juice| %>
        <div class="col-xs-3 col-md-3 col-centered juice">
          <h3 align="center"><%= link_to juice.name, juice_path(juice) %></h3>
          <% juice.produce.each do |prod| %>
          <p align="center"><%= prod.juice_produce.first.quantity %> <%= prod.name %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <br></br>
    <h1 align="center"><%= link_to "Create a New Juice", new_user_juice_path(current_user), class: "btn btn-default" %></h1>
  </div>
</div>

app/views/juices/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1 align="center">New Juice</h1>
  <%= bootstrap_form_for @juice do |f| %>
    <h3><%= f.text_field :name, placeholder: "Juice Name" %></h3>
    <label><h3 align="center">Ingredients:</h2></label>
    <div class="row">
      <% 4.times do %>
      <div class="col-xs-3">
        <%= f.fields_for :produce, @juice.produce.build do |prod_builder| %>
          <%= prod_builder.select 'name', options_from_collection_for_select(@produce, 'id', 'name'), include_blank: true, placeholder: "Produce..." %>
          <%= prod_builder.fields_for :juice_produce, @juice.juice_produce.build do |jp_builder| %>
            <%= jp_builder.number_field :quantity, min: 1, placeholder: "Quantity" %>
        <% end %>
        <% end %>
      </div>
      <% end %>
    </div>
    <div class="row">
      <h4 align="center">Can't find your ingredient? Add it here:</h4>
      <% 4.times do %>
        <div class="col-xs-3">
          <%= f.fields_for :produce, @juice.produce.build do |prod_form| %>
            <%= prod_form.text_field :name, placeholder: "Produce..." %>
            <%= prod_form.fields_for :juice_produce, @juice.juice_produce.build do |jp_form| %>
              <%= jp_form.number_field :quantity, min: 1, placeholder: "Quantity" %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <%= f.submit %>
  </div>
  <% end %>

</div>

app/views/juices/show.html.erb
<div class="juice-show-page">
  <div class="juice-show">
    <%= render partial: 'shared/jumbotron', locals: {jumbo: 'jumbotron-juice', header: @juice.name} %>
    <div class="container juice-produce">
      <div class="row row-centered">
        <h2 align="center">Ingredients</h2>
        <div class="col-xs-8 col-sm-8 col-md-8 col-xs-offset-2 col-sm-offset-2 col-md-offset-2 juice-produce">
          <% @juice_produce.each do |juice_prod| %>
          <div class="col-xs-4 col-sm-4 col-md-4 col-centered">
            <h3 align="center" class="produceQuantity"><%= juice_prod.quantity %> <%= juice_prod.produce.name %></h3>
            <div class="produce-index-img text-center">
              <%= link_to image_tag(juice_prod.produce.image.thumb.url), produce_path(juice_prod.produce) %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="juice-links">
      <div class="col-xs-6 col-md-6 col-md-offset-3">
        <div class="col-xs-4">
          <h4 align="left"><a class="editJuice" href="/juices/<%= @juice.id %>/edit">Edit Juice</a></h4>
        </div>
        <div class="col-xs-4">
          <% if current_user.id == @juice.user_id %>
          <h4 align="center"><a class="deleteJuice" rel="nofollow" data-method="delete" href="/juices/19">Delete Juice</a></h4>
          <% end %>
        </div>
        <div class="col-xs-4">
          <p align="right"><a class="userJuice" href="/users/<%= @juice.id %>/juices">Created by <%= @juice.user.name %></a></p>
        </div>
      </div>
    </div>
    <br>
    <div class="prev-next">
      <div class="col-md-6 col-md-offset-3">
        <div class="col-md-4 col-md-offset-4" align="center">
          <a href="#" class="js-previous" data-id="<%= @juice.id %>">Previous Juice</a>
          ------ <a href="#" class="js-next" data-id="<%= @juice.id %>" last-id="<%= @last_juice_id %>">Next Juice</a>
        </div>
      </div>
    </div>
  </div>

  <div class="container comments">
    <h2 align="center">Leave a Comment</h2>
    <% @juice_comments.each do |comment| %>
    <%= render partial: 'comments/comments', locals: {comment: comment} %>
    <% end %>
  </div>
  <div class="container">
    <div class="row js-commentForm">
      <div class="col-sm-8 col-sm-offset-2">
        <%= bootstrap_form_for(@comment, label_errors: true) do |f| %>
        <ul class="error"></ul>
        <%= f.hidden_field :juice_id, value: @juice.id %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="col-sm-12">
          <div class="col-sm-9">
            <%= f.text_area :content, hide_label: true, placeholder: "Your Comment", class: "panel panel-white post panel-shadow comment-area" %>
          </div>
          <div class="col-sm-2">
            <%= f.submit class: 'btn btn-default js-formSubmit' %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script id="juice-produce-template" type="text/x-handlebars-template">
  <div class="juice-show-page">
    <div class="juice-show">
      <div class="jumbotron jumbotron-juice jumbo-juice">
        <div class="img"></div>
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <h1 class="jumbo-header" align="center">{{name}}</h1>
            </div>
          </div>
        </div>
      </div>
      <br><br />
      <div class="row">
        <div class="col-md-8 col-md-offset-2"></div>
      </div>
      <hr class="hr-green hr-green-juice">
      <div class="container juice-produce">
        <div class="row row-centered">
          <h2 align="center">Ingredients</h2>
          <div class="col-xs-8 col-md-8 col-md-offset-2">
            {{#each juiceProduce}}
            <div class="col-xs-4 col-centered">
              <h3 align="center" class="produceQuantity">{{quantity}} {{name}}</h3>
              <div class="produce-index-img text-center">
                <a href="/produce/{{id}}"><img src="{{image}}" alt="Thumb {{name}}" /></a>
              </div>
            </div>
            {{/each}}

          </div>
        </div>
      </div>
      <br>
      <div class="juice-links">
        <div class="col-xs-6 col-md-6 col-md-offset-3">
          <div class="col-xs-4">
            <h4 align="left"><a class="editJuice" href="/juices/{{id}}/edit">Edit Juice</a></h4>
          </div>
          <div class="col-xs-4">
          </div>
          <div class="col-xs-4">
            <p align="right"><a class="userJuice" href="/users/{{userId}}/juices">Created by {{userName}}</a></p>
          </div>
        </div>
      </div>
      <div class="prev-next">
        <div class="col-md-6 col-md-offset-3">
          <div class="col-md-4 col-md-offset-4" align="center">
            <a href="#" class="js-previous" data-id="{{id}}">Previous Juice</a>
            ------ <a href="#" class="js-next" data-id="{{id}}" last-id="<%= @last_juice_id %>">Next Juice</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="container comment-container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h2 align="center">Leave a Comment</h2>
      </div>
    </div>
  </div>
</script>

<script id="comment-template" type="text/x-handlebars-template">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div class="panel panel-white post panel-shadow">
          <div class="post-heading">
            <div class="pull-left image">
              <img src="http://www.gravatar.com/avatar/{{email}}" class="img-circle avatar" alt="Gravatar">
            </div>
            <div class="pull-left meta">
              <div class="title h5">
                <a href="/users.{{userId}}"> {{userName}}  commented on</a>
              </div>
              <h6 class="text-muted time">{{formattedDate}}</h6>
            </div>
          </div>
          <br>
          <div class="post-description">
            <p>{{commentContent}}</p>
          </div>
        </div>
      </div>
    </div>
</script>

<script type="text/javascript">
$(function() {
  previous();
  next();
  Comment.ready();
})
</script>